project_name: antigravity-403-plugin

before:
  hooks:
    - go mod tidy

builds:
  - id: plugin
    main: ./cmd/plugin
    binary: antigravity-403-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - README_CN.md
      - LICENSE
      - config.example.yaml

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: git
